<?php
require_once __DIR__ . '/bootstrap.php';

soc_require_admin();

function soc_report_copy(): array
{
    if (soc_current_language() === 'en') {
        return [
            'title' => 'SOC PDF Report',
            'intro' => 'Generate a clean synthesis report from filtered Mini-SIEM alerts.',
            'pdf_title' => 'Mini-SOC - Security report',
            'period' => 'Period',
            'generated_at' => 'Generated at',
            'summary' => 'Summary',
            'total_alerts' => 'Total alerts',
            'global_score' => 'Global score',
            'critical' => 'Critical',
            'high' => 'High',
            'medium' => 'Medium',
            'low' => 'Low',
            'no_alerts' => 'No alert for this report.',
            'attack_distribution' => 'Attack distribution',
            'attack_percentages' => 'Attack percentages',
            'dominant_attack' => 'Dominant attack',
            'risk_level' => 'Risk level',
            'attack_timeline' => 'Attack timeline',
            'timeline_hint' => 'Alerts by period and attack type',
            'period_min' => 'Min',
            'period_max' => 'Max',
            'mitre_detected' => 'MITRE detected',
            'detected_cases' => 'Detected cases',
            'incident_analysis' => 'Incident analysis',
            'responses' => 'Recommended response',
            'improvements' => 'Improvements',
            'cases' => 'case(s)',
            'main_sources' => 'Main sources',
            'latest_seen' => 'Latest seen',
            'generated_by' => 'Generated by Mini-SOC',
            'page' => 'Page',
            'params' => 'Report parameters',
            'date_from' => 'Start date',
            'date_to' => 'End date',
            'attack_type' => 'Attack type',
            'severity' => 'Severity',
            'status' => 'Status',
            'all' => 'All',
            'preview' => 'Preview',
            'generate_pdf' => 'Generate PDF',
            'filename' => 'mini-soc-report.pdf',
        ];
    }

    return [
        'title' => 'Rapport SOC PDF',
        'intro' => 'Générer un rapport de synthèse clair à partir des alertes Mini-SIEM filtrées.',
        'pdf_title' => 'Mini-SOC - Rapport de securite',
        'period' => 'Periode',
        'generated_at' => 'Genere le',
        'summary' => 'Resume',
        'total_alerts' => 'Total alertes',
        'global_score' => 'Score global',
        'critical' => 'Critique',
        'high' => 'Haute',
        'medium' => 'Moyenne',
        'low' => 'Basse',
        'no_alerts' => 'Aucune alerte pour ce rapport.',
        'attack_distribution' => 'Distribution des attaques',
        'attack_percentages' => 'Pourcentages des attaques',
        'dominant_attack' => 'Attaque dominante',
        'risk_level' => 'Niveau risque',
        'attack_timeline' => 'Timeline des attaques',
        'timeline_hint' => 'Alertes par periode et type attaque',
        'period_min' => 'Min',
        'period_max' => 'Max',
        'mitre_detected' => 'MITRE detectes',
        'detected_cases' => 'Cas detectes',
        'incident_analysis' => 'Analyse incident',
        'responses' => 'Reponse recommandee',
        'improvements' => 'Ameliorations',
        'cases' => 'cas',
        'main_sources' => 'Sources principales',
        'latest_seen' => 'Dernier signal',
        'generated_by' => 'Genere par Mini-SOC',
        'page' => 'Page',
        'params' => 'Paramètres du rapport',
        'date_from' => 'Date début',
        'date_to' => 'Date fin',
        'attack_type' => 'Type attaque',
        'severity' => 'Gravité',
        'status' => 'Statut',
        'all' => 'Toutes',
        'preview' => 'Prévisualiser',
        'generate_pdf' => 'Générer PDF',
        'filename' => 'mini-soc-rapport.pdf',
    ];
}

function soc_report_recommendations(): array
{
    $file = __DIR__ . '/report_recommendations.json';
    if (!is_file($file)) {
        return [];
    }

    $json = json_decode((string)file_get_contents($file), true);
    return is_array($json) ? $json : [];
}

function soc_report_options(array $source): array
{
    $display = soc_alert_display_settings();
    return [
        'include_mitre' => !empty($display['show_mitre_id'])
            || !empty($display['show_mitre_tactic'])
            || !empty($display['show_mitre_technique']),
        'include_response' => !empty($display['show_recommended_response']),
    ];
}

function soc_report_case_key(array $alert): string
{
    $label = strtolower((string)($alert['attack_label'] ?? $alert['attack_type'] ?? ''));
    if (str_contains($label, 'sql')) {
        return 'SQLi';
    }
    if (str_contains($label, 'xss') || str_contains($label, 'cross-site')) {
        return 'XSS';
    }
    if (str_contains($label, 'brute')) {
        return 'BruteForce';
    }
    return '';
}

function soc_report_case_label(string $key): string
{
    return [
        'SQLi' => 'SQLi',
        'XSS' => 'XSS',
        'BruteForce' => 'Brute Force',
    ][$key] ?? $key;
}

function soc_report_case_recommendation(string $key, array $recommendations): array
{
    $lang = soc_current_language();
    $data = $recommendations[$key][$lang] ?? $recommendations[$key]['fr'] ?? [];
    return [
        'incident' => (string)($data['incident'] ?? ''),
        'responses' => array_values(array_filter((array)($data['responses'] ?? []))),
        'improvements' => array_values(array_filter((array)($data['improvements'] ?? []))),
    ];
}

function soc_report_cases(array $alerts): array
{
    $recommendations = soc_report_recommendations();
    $mitreMap = soc_mitre_map();
    $cases = [];

    foreach ($alerts as $alert) {
        $key = soc_report_case_key($alert);
        if ($key === '') {
            continue;
        }

        if (!isset($cases[$key])) {
            $mitre = $mitreMap[$key] ?? [];
            $cases[$key] = [
                'key' => $key,
                'label' => soc_report_case_label($key),
                'count' => 0,
                'severity' => strtoupper((string)($alert['severity'] ?? $mitre['severity'] ?? '')),
                'latest_seen' => $alert['timestamp'] ?? '',
                'sources' => [],
                'mitre_id' => (string)($alert['mitre_id'] ?? $mitre['mitre_id'] ?? ''),
                'mitre_tactic' => (string)($alert['mitre_tactic'] ?? $mitre['tactic'] ?? ''),
                'mitre_technique' => (string)($alert['mitre_technique'] ?? $mitre['technique'] ?? ''),
            ] + soc_report_case_recommendation($key, $recommendations);
        }

        $cases[$key]['count']++;
        if (soc_severity_rank((string)($alert['severity'] ?? '')) > soc_severity_rank((string)$cases[$key]['severity'])) {
            $cases[$key]['severity'] = strtoupper((string)$alert['severity']);
        }
        if (!empty($alert['timestamp'])) {
            $cases[$key]['latest_seen'] = $alert['timestamp'];
        }
        if (!empty($alert['source_ip'])) {
            $cases[$key]['sources'][(string)$alert['source_ip']] = true;
        }
    }

    foreach ($cases as &$case) {
        $case['sources'] = array_slice(array_keys($case['sources']), 0, 5);
    }
    unset($case);

    return array_values($cases);
}

function soc_report_attack_percentages(array $stats): array
{
    $total = max(0, (int)($stats['total'] ?? 0));
    $items = [
        ['key' => 'sqli', 'label' => 'SQLi', 'count' => (int)($stats['sqli'] ?? 0), 'color' => '#dc2626'],
        ['key' => 'xss', 'label' => 'XSS', 'count' => (int)($stats['xss'] ?? 0), 'color' => '#7c3aed'],
        ['key' => 'bruteforce', 'label' => 'Brute Force', 'count' => (int)($stats['brute_force'] ?? 0), 'color' => '#f59e0b'],
    ];

    foreach ($items as &$item) {
        $item['percent'] = $total > 0 ? round(($item['count'] / $total) * 100, 1) : 0.0;
    }
    unset($item);

    return $items;
}

function soc_report_dominant_attack(array $percentages): array
{
    $dominant = ['label' => '-', 'count' => 0, 'percent' => 0.0, 'color' => '#2563eb'];
    foreach ($percentages as $item) {
        if ((int)$item['count'] > (int)$dominant['count']) {
            $dominant = $item;
        }
    }
    return $dominant;
}

function soc_report_attack_timeline(array $alerts, array $filters): array
{
    $from = DateTime::createFromFormat('Y-m-d H:i:s', (string)$filters['date_from'] . ' 00:00:00') ?: new DateTime('-6 days');
    $to = DateTime::createFromFormat('Y-m-d H:i:s', (string)$filters['date_to'] . ' 23:59:59') ?: new DateTime();
    if ($to < $from) {
        [$from, $to] = [$to, $from];
    }

    $days = (int)$from->diff($to)->format('%a');
    $group = $days > 31 ? 'month' : 'day';
    $periods = [];
    $cursor = clone $from;
    $end = clone $to;

    if ($group === 'month') {
        $cursor->modify('first day of this month')->setTime(0, 0, 0);
        $end->modify('first day of this month')->setTime(0, 0, 0);
    } else {
        $cursor->setTime(0, 0, 0);
        $end->setTime(0, 0, 0);
    }

    while ($cursor <= $end) {
        $key = $cursor->format($group === 'month' ? 'Y-m' : 'Y-m-d');
        $periods[$key] = [
            'key' => $key,
            'label' => $cursor->format($group === 'month' ? 'm/Y' : 'd/m'),
            'sqli' => 0,
            'xss' => 0,
            'bruteforce' => 0,
            'total' => 0,
        ];
        $cursor->modify($group === 'month' ? '+1 month' : '+1 day');
    }

    foreach ($alerts as $alert) {
        try {
            $date = new DateTime((string)($alert['timestamp'] ?? ''));
        } catch (Exception $exception) {
            continue;
        }

        $key = $date->format($group === 'month' ? 'Y-m' : 'Y-m-d');
        if (!isset($periods[$key])) {
            continue;
        }

        $case = soc_report_case_key($alert);
        $token = [
            'SQLi' => 'sqli',
            'XSS' => 'xss',
            'BruteForce' => 'bruteforce',
        ][$case] ?? '';

        if ($token === '') {
            continue;
        }

        $periods[$key][$token]++;
        $periods[$key]['total']++;
    }

    $points = array_values($periods);
    $totals = array_map(static fn(array $point): int => (int)$point['total'], $points);
    $nonZero = array_values(array_filter($totals, static fn(int $total): bool => $total > 0));

    return [
        'group' => $group,
        'points' => $points,
        'max' => $totals ? max($totals) : 0,
        'min' => $nonZero ? min($nonZero) : 0,
    ];
}

function soc_report_payload(array $filters, array $options): array
{
    $rawAlerts = soc_fetch_alert_history($filters);
    $alerts = array_map('soc_alert_payload', $rawAlerts);
    $stats = soc_dashboard_stats($filters);
    $attackPercentages = soc_report_attack_percentages($stats);
    return [
        'stats' => $stats,
        'alerts' => $alerts,
        'cases' => soc_report_cases($alerts),
        'detection' => soc_detection_status(),
        'attack_percentages' => $attackPercentages,
        'dominant_attack' => soc_report_dominant_attack($attackPercentages),
        'attack_timeline' => soc_report_attack_timeline($rawAlerts, $filters),
    ];
}

function soc_report_text_lines(array $filters, array $options): array
{
    $copy = soc_report_copy();
    $payload = soc_report_payload($filters, $options);
    $stats = $payload['stats'];
    $detection = $payload['detection'];
    $lines = [
        $copy['period'] . ': ' . $filters['date_from'] . ' - ' . $filters['date_to'],
        $copy['generated_at'] . ': ' . date('d/m/Y H:i:s'),
        '',
        $copy['summary'],
        $copy['total_alerts'] . ': ' . $stats['total'],
        $copy['global_score'] . ': ' . $detection['score_global'] . ' / ' . $detection['score_level'],
        'SQLi: ' . $stats['sqli'],
        'XSS: ' . $stats['xss'],
        'Brute Force: ' . $stats['brute_force'],
        $copy['critical'] . ': ' . ($stats['severity']['CRITICAL'] ?? 0),
        $copy['high'] . ': ' . ($stats['severity']['HIGH'] ?? 0),
        $copy['medium'] . ': ' . ($stats['severity']['MEDIUM'] ?? 0),
        $copy['low'] . ': ' . ($stats['severity']['LOW'] ?? 0),
        '',
        $copy['attack_percentages'],
    ];

    foreach ($payload['attack_percentages'] as $item) {
        $lines[] = $item['label'] . ': ' . $item['count'] . ' (' . $item['percent'] . '%)';
    }

    $lines[] = $copy['dominant_attack'] . ': ' . $payload['dominant_attack']['label'] . ' (' . $payload['dominant_attack']['percent'] . '%)';
    $lines[] = '';
    $lines[] = $copy['detected_cases'];

    if (!$payload['cases']) {
        $lines[] = $copy['no_alerts'];
        return $lines;
    }

    foreach ($payload['cases'] as $case) {
        $lines[] = '';
        $lines[] = $case['label'] . ': ' . $case['count'] . ' ' . $copy['cases'] . ' | ' . $copy['severity'] . ': ' . soc_severity_label($case['severity']);
        $lines[] = $copy['latest_seen'] . ': ' . $case['latest_seen'];
        if ($case['sources']) {
            $lines[] = $copy['main_sources'] . ': ' . implode(', ', $case['sources']);
        }
        if ($options['include_mitre']) {
            $mitreParts = array_values(array_filter([$case['mitre_id'], $case['mitre_tactic'], $case['mitre_technique']]));
            if ($mitreParts) {
                $lines[] = $copy['mitre_detected'] . ': ' . implode(' - ', $mitreParts);
            }
        }
        if ($case['incident'] !== '') {
            $lines[] = $copy['incident_analysis'] . ': ' . $case['incident'];
        }
        if ($options['include_response'] && $case['responses']) {
            $lines[] = $copy['responses'] . ':';
            foreach ($case['responses'] as $response) {
                $lines[] = '- ' . $response;
            }
        }
        if ($case['improvements']) {
            $lines[] = $copy['improvements'] . ':';
            foreach ($case['improvements'] as $improvement) {
                $lines[] = '- ' . $improvement;
            }
        }
    }

    return $lines;
}

function soc_pdf_escape(string $text): string
{
    $text = str_replace(["\r", "\n", "\t"], ' ', $text);
    if (function_exists('iconv')) {
        $converted = iconv('UTF-8', 'Windows-1252//TRANSLIT', $text);
        if ($converted !== false) {
            $text = $converted;
        }
    }
    return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $text);
}

function soc_wrap_report_line(string $line, int $limit = 94): array
{
    if ($line === '') {
        return [''];
    }
    $wrapped = wordwrap($line, $limit, "\n", true);
    return explode("\n", $wrapped);
}

function soc_pdf_rgb(string $hex, string $operator): string
{
    $hex = ltrim($hex, '#');
    if (strlen($hex) === 3) {
        $hex = $hex[0] . $hex[0] . $hex[1] . $hex[1] . $hex[2] . $hex[2];
    }
    $r = hexdec(substr($hex, 0, 2)) / 255;
    $g = hexdec(substr($hex, 2, 2)) / 255;
    $b = hexdec(substr($hex, 4, 2)) / 255;
    return sprintf('%.4f %.4f %.4f %s', $r, $g, $b, $operator);
}

function soc_pdf_rect(float $x, float $y, float $w, float $h, string $fill, ?string $stroke = null, float $lineWidth = 1): string
{
    $py = 842 - $y - $h;
    $cmd = 'q ' . soc_pdf_rgb($fill, 'rg') . ' ';
    if ($stroke !== null) {
        $cmd .= soc_pdf_rgb($stroke, 'RG') . ' ' . $lineWidth . ' w ';
    }
    $cmd .= sprintf('%.2f %.2f %.2f %.2f re %s Q', $x, $py, $w, $h, $stroke === null ? 'f' : 'B');
    return $cmd . "\n";
}

function soc_pdf_text(float $x, float $y, string $text, float $size = 10, string $color = '#111827', bool $bold = false): string
{
    $font = $bold ? 'F2' : 'F1';
    $py = 842 - $y;
    return 'BT /' . $font . ' ' . $size . ' Tf ' . soc_pdf_rgb($color, 'rg') . ' ' .
        sprintf('%.2f %.2f Td ', $x, $py) . '(' . soc_pdf_escape($text) . ") Tj ET\n";
}

function soc_pdf_wrap_text(string $text, float $maxWidth, float $size): array
{
    $text = trim((string)preg_replace('/\s+/', ' ', $text));
    if ($text === '') {
        return [];
    }
    $chars = max(18, (int)floor($maxWidth / max(4.5, $size * 0.52)));
    return explode("\n", wordwrap($text, $chars, "\n", true));
}

function soc_pdf_multiline(float $x, float $y, string $text, float $maxWidth, float $size, string $color, bool $bold = false, float $lineHeight = 12): array
{
    $lines = soc_pdf_wrap_text($text, $maxWidth, $size);
    $cmd = '';
    foreach ($lines as $index => $line) {
        $cmd .= soc_pdf_text($x, $y + ($index * $lineHeight), $line, $size, $color, $bold);
    }
    return [$cmd, count($lines) * $lineHeight];
}

function soc_pdf_card(float $x, float $y, float $w, float $h, string $accent = '#2563eb'): string
{
    return soc_pdf_rect($x, $y, $w, $h, '#ffffff', '#dbe4f0', 0.8)
        . soc_pdf_rect($x, $y, $w, 5, $accent);
}

function soc_pdf_severity_color(string $severity): string
{
    return [
        'CRITICAL' => '#dc2626',
        'HIGH' => '#f59e0b',
        'MEDIUM' => '#eab308',
        'LOW' => '#16a34a',
    ][strtoupper($severity)] ?? '#2563eb';
}

function soc_pdf_header(array $copy, array $filters, array $payload, int $page): string
{
    $cmd = soc_pdf_rect(0, 0, 595, 842, '#f4f7fb');
    $cmd .= soc_pdf_rect(0, 0, 595, 112, '#1a237e');
    $cmd .= soc_pdf_text(36, 42, $copy['pdf_title'], 21, '#ffffff', true);
    $cmd .= soc_pdf_text(36, 65, $copy['generated_by'], 9, '#dbeafe');
    $cmd .= soc_pdf_text(382, 37, $copy['period'] . ': ' . $filters['date_from'] . ' - ' . $filters['date_to'], 9, '#ffffff');
    $cmd .= soc_pdf_text(382, 56, $copy['generated_at'] . ': ' . date('d/m/Y H:i:s'), 8.5, '#dbeafe');
    $cmd .= soc_pdf_text(36, 820, 'Mini-SOC', 8, '#64748b', true);
    $cmd .= soc_pdf_text(505, 820, $copy['page'] . ' ' . $page, 8, '#64748b');
    return $cmd;
}

function soc_pdf_stat_card(float $x, float $y, float $w, string $label, string $value, string $accent): string
{
    $valueSize = strlen($value) > 9 ? 14 : 19;
    return soc_pdf_card($x, $y, $w, 74, $accent)
        . soc_pdf_text($x + 14, $y + 25, $label, 9, '#64748b', true)
        . soc_pdf_text($x + 14, $y + 54, $value, $valueSize, '#111827', true);
}

function soc_pdf_bar(float $x, float $y, float $w, float $percent, string $color): string
{
    $fillWidth = $w * max(0, min(100, $percent)) / 100;
    return soc_pdf_rect($x, $y, $w, 8, '#e2e8f0')
        . soc_pdf_rect($x, $y, $fillWidth, 8, $color);
}

function soc_pdf_attack_timeline_graph(float $x, float $y, array $copy, array $payload): string
{
    $timeline = $payload['attack_timeline'] ?? ['points' => [], 'max' => 0, 'min' => 0];
    $points = array_slice((array)($timeline['points'] ?? []), -14);
    $max = max(1, (int)($timeline['max'] ?? 0));
    $min = max(0, (int)($timeline['min'] ?? 0));
    $cmd = soc_pdf_card($x, $y, 523, 238, '#0ea5e9');
    $cmd .= soc_pdf_text($x + 18, $y + 29, $copy['attack_timeline'], 14, '#111827', true);
    $cmd .= soc_pdf_text($x + 18, $y + 47, $copy['timeline_hint'], 8.5, '#64748b');
    $cmd .= soc_pdf_text($x + 380, $y + 29, $copy['period_min'] . ': ' . $min . '   ' . $copy['period_max'] . ': ' . (int)($timeline['max'] ?? 0), 8.5, '#334155', true);

    $legendX = $x + 350;
    $legendY = $y + 48;
    $legend = [
        ['label' => 'SQLi', 'color' => '#dc2626'],
        ['label' => 'XSS', 'color' => '#7c3aed'],
        ['label' => 'Brute Force', 'color' => '#f59e0b'],
    ];
    foreach ($legend as $index => $item) {
        $lx = $legendX + ($index * 56);
        $cmd .= soc_pdf_rect($lx, $legendY - 8, 8, 8, $item['color']);
        $cmd .= soc_pdf_text($lx + 12, $legendY, $item['label'], 7.5, '#334155', true);
    }

    $chartX = $x + 36;
    $chartY = $y + 72;
    $chartW = 455;
    $chartH = 118;
    for ($line = 0; $line <= 4; $line++) {
        $lineY = $chartY + ($line * ($chartH / 4));
        $cmd .= soc_pdf_rect($chartX, $lineY, $chartW, 0.5, '#e2e8f0');
    }

    $count = max(1, count($points));
    $gap = $count > 10 ? 8 : 14;
    $barW = min(26, max(10, ($chartW - (($count - 1) * $gap)) / $count));
    $usedW = ($count * $barW) + (($count - 1) * $gap);
    $startX = $chartX + max(0, ($chartW - $usedW) / 2);
    $segments = [
        'sqli' => '#dc2626',
        'xss' => '#7c3aed',
        'bruteforce' => '#f59e0b',
    ];

    foreach ($points as $index => $point) {
        $barX = $startX + ($index * ($barW + $gap));
        $cmd .= soc_pdf_rect($barX, $chartY, $barW, $chartH, '#eef2f8');
        $bottom = $chartY + $chartH;
        foreach ($segments as $key => $color) {
            $value = (int)($point[$key] ?? 0);
            if ($value <= 0) {
                continue;
            }
            $height = max(2, ($value / $max) * $chartH);
            $top = $bottom - $height;
            $cmd .= soc_pdf_rect($barX, $top, $barW, $height, $color);
            $bottom = $top;
        }
        $cmd .= soc_pdf_text($barX - 4, $chartY + $chartH + 15, (string)($point['label'] ?? ''), 6.8, '#64748b');
    }

    $cmd .= soc_pdf_text($x + 18, $y + 218, $copy['dominant_attack'] . ': ' . $payload['dominant_attack']['label'] . ' (' . $payload['dominant_attack']['percent'] . '%)', 9, '#1d4ed8', true);
    return $cmd;
}

function soc_pdf_build_document(array $pages): string
{
    $pageCount = count($pages);
    $pageStart = 5;
    $contentStart = $pageStart + $pageCount;
    $objects = [
        1 => '<< /Type /Catalog /Pages 2 0 R >>',
        3 => '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
        4 => '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>',
    ];
    $kids = [];

    foreach ($pages as $index => $content) {
        $pageId = $pageStart + $index;
        $contentId = $contentStart + $index;
        $kids[] = $pageId . ' 0 R';
        $objects[$pageId] = "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents $contentId 0 R >>";
        $objects[$contentId] = "<< /Length " . strlen($content) . " >>\nstream\n" . $content . "\nendstream";
    }

    $objects[2] = '<< /Type /Pages /Kids [' . implode(' ', $kids) . '] /Count ' . $pageCount . ' >>';
    ksort($objects);

    $pdf = "%PDF-1.4\n";
    $offsets = [0];
    foreach ($objects as $id => $object) {
        $offsets[$id] = strlen($pdf);
        $pdf .= $id . " 0 obj\n" . $object . "\nendobj\n";
    }
    $xref = strlen($pdf);
    $pdf .= "xref\n0 " . (count($objects) + 1) . "\n";
    $pdf .= "0000000000 65535 f \n";
    for ($i = 1; $i <= count($objects); $i++) {
        $pdf .= sprintf("%010d 00000 n \n", $offsets[$i]);
    }
    $pdf .= "trailer\n<< /Size " . (count($objects) + 1) . " /Root 1 0 R >>\nstartxref\n" . $xref . "\n%%EOF";
    return $pdf;
}

function soc_send_pdf_report(array $filters, array $options): void
{
    $copy = soc_report_copy();
    $payload = soc_report_payload($filters, $options);
    $stats = $payload['stats'];
    $detection = $payload['detection'];
    $pages = [];
    $page = 0;
    $content = '';
    $y = 0.0;

    $startPage = function () use (&$pages, &$page, &$content, &$y, $copy, $filters, $payload): void {
        if ($page > 0) {
            $pages[] = $content;
        }
        $page++;
        $content = soc_pdf_header($copy, $filters, $payload, $page);
        $y = 132;
    };

    $ensure = function (float $height) use (&$startPage, &$y): void {
        if ($y + $height > 795) {
            $startPage();
        }
    };

    $startPage();

    $cardW = 123;
    $content .= soc_pdf_stat_card(36, $y, $cardW, $copy['total_alerts'], (string)$stats['total'], '#2563eb');
    $content .= soc_pdf_stat_card(169, $y, $cardW, $copy['critical'], (string)($stats['severity']['CRITICAL'] ?? 0), '#dc2626');
    $content .= soc_pdf_stat_card(302, $y, $cardW, $copy['high'], (string)($stats['severity']['HIGH'] ?? 0), '#f59e0b');
    $content .= soc_pdf_stat_card(435, $y, $cardW, $copy['global_score'], $detection['score_global'] . ' / ' . $detection['score_level'], '#7c3aed');
    $y += 98;

    $content .= soc_pdf_card(36, $y, 523, 128, '#2563eb');
    $content .= soc_pdf_text(54, $y + 28, $copy['attack_percentages'], 14, '#111827', true);
    $dominant = $payload['dominant_attack'];
    $content .= soc_pdf_text(370, $y + 28, $copy['dominant_attack'] . ': ' . $dominant['label'] . ' (' . $dominant['percent'] . '%)', 9, '#334155', true);
    $rowY = $y + 55;
    foreach ($payload['attack_percentages'] as $item) {
        $content .= soc_pdf_text(54, $rowY + 8, $item['label'], 10, '#111827', true);
        $content .= soc_pdf_bar(150, $rowY, 270, (float)$item['percent'], $item['color']);
        $content .= soc_pdf_text(435, $rowY + 8, $item['count'] . ' (' . $item['percent'] . '%)', 9, '#334155', true);
        $rowY += 25;
    }
    $y += 152;

    $content .= soc_pdf_text(36, $y, $copy['detected_cases'], 15, '#111827', true);
    $y += 18;

    if (!$payload['cases']) {
        $content .= soc_pdf_card(36, $y, 523, 58, '#94a3b8');
        $content .= soc_pdf_text(54, $y + 34, $copy['no_alerts'], 11, '#334155', true);
        $y += 78;
    }

    foreach ($payload['cases'] as $case) {
        $incidentLines = soc_pdf_wrap_text($case['incident'], 474, 9);
        $responseLines = [];
        foreach ($case['responses'] as $response) {
            foreach (soc_pdf_wrap_text('- ' . $response, 462, 8.5) as $line) {
                $responseLines[] = $line;
            }
        }
        $improvementLines = [];
        foreach ($case['improvements'] as $improvement) {
            foreach (soc_pdf_wrap_text('- ' . $improvement, 462, 8.5) as $line) {
                $improvementLines[] = $line;
            }
        }

        $caseHeight = 136 + (count($incidentLines) * 11);
        if ($options['include_response'] && $responseLines) {
            $caseHeight += 22 + (count($responseLines) * 11);
        }
        if ($improvementLines) {
            $caseHeight += 22 + (count($improvementLines) * 11);
        }
        $caseHeight = max(178, $caseHeight);

        $ensure($caseHeight + 18);
        $accent = soc_pdf_severity_color((string)$case['severity']);
        $content .= soc_pdf_card(36, $y, 523, $caseHeight, $accent);
        $content .= soc_pdf_text(54, $y + 27, $case['label'] . ' - ' . $case['count'] . ' ' . $copy['cases'], 13, '#111827', true);
        $content .= soc_pdf_text(398, $y + 27, soc_severity_label($case['severity']), 10, $accent, true);
        $content .= soc_pdf_text(54, $y + 47, $copy['latest_seen'] . ': ' . $case['latest_seen'], 8.5, '#64748b');
        if ($case['sources']) {
            $content .= soc_pdf_text(54, $y + 63, $copy['main_sources'] . ': ' . implode(', ', $case['sources']), 8.5, '#64748b');
        }
        if ($options['include_mitre']) {
            $mitreParts = array_values(array_filter([$case['mitre_id'], $case['mitre_tactic'], $case['mitre_technique']]));
            if ($mitreParts) {
                $content .= soc_pdf_text(54, $y + 81, $copy['mitre_detected'] . ': ' . implode(' - ', $mitreParts), 8.5, '#1d4ed8', true);
            }
        }

        $yy = $y + 101;
        $content .= soc_pdf_text(54, $yy, $copy['incident_analysis'], 9, '#111827', true);
        $yy += 14;
        foreach ($incidentLines as $line) {
            $content .= soc_pdf_text(66, $yy, $line, 8.5, '#334155');
            $yy += 11;
        }

        if ($options['include_response'] && $responseLines) {
            $yy += 8;
            $content .= soc_pdf_text(54, $yy, $copy['responses'], 9, '#111827', true);
            $yy += 14;
            foreach ($responseLines as $line) {
                $content .= soc_pdf_text(66, $yy, $line, 8.5, '#334155');
                $yy += 11;
            }
        }

        if ($improvementLines) {
            $yy += 8;
            $content .= soc_pdf_text(54, $yy, $copy['improvements'], 9, '#111827', true);
            $yy += 14;
            foreach ($improvementLines as $line) {
                $content .= soc_pdf_text(66, $yy, $line, 8.5, '#334155');
                $yy += 11;
            }
        }

        $y += $caseHeight + 18;
    }

    $ensure(262);
    $content .= soc_pdf_attack_timeline_graph(36, $y, $copy, $payload);
    $y += 262;

    $pages[] = $content;
    $pdf = soc_pdf_build_document($pages);

    header('Content-Type: application/pdf');
    header('Content-Disposition: attachment; filename="' . $copy['filename'] . '"');
    header('Content-Length: ' . strlen($pdf));
    echo $pdf;
    exit;
}

$filters = soc_normalize_filters($_GET);
$options = soc_report_options($_GET);

if (($_GET['format'] ?? '') === 'pdf') {
    soc_send_pdf_report($filters, $options);
}

$copy = soc_report_copy();
$payload = soc_report_payload($filters, $options);
$stats = $payload['stats'];
$detection = $payload['detection'];
$attackPercentages = [];
foreach ($payload['attack_percentages'] as $item) {
    $attackPercentages[$item['key']] = $item;
}
$severityPercentages = [];
$severityTotal = max(0, (int)($stats['total'] ?? 0));
foreach (['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'] as $severity) {
    $count = (int)($stats['severity'][$severity] ?? 0);
    $severityPercentages[] = [
        'label' => soc_severity_label($severity),
        'count' => $count,
        'percent' => $severityTotal > 0 ? round(($count / $severityTotal) * 100, 1) : 0,
        'token' => strtolower($severity),
    ];
}

soc_shell_start($copy['title'], 'reports');
?>
<section class="hero-row compact">
    <div>
        <h1><?= soc_e($copy['title']) ?></h1>
        <p><?= soc_e($copy['intro']) ?></p>
    </div>
</section>

<section class="report-grid">
    <article class="panel-card">
        <div class="panel-head">
            <h2><?= soc_e($copy['params']) ?></h2>
            <?= soc_icon('file') ?>
        </div>
        <form class="report-form" method="get">
            <input type="hidden" name="report_options" value="1">
            <label>
                <span><?= soc_e($copy['date_from']) ?></span>
                <input type="date" name="date_from" value="<?= soc_e($filters['date_from']) ?>">
            </label>
            <label>
                <span><?= soc_e($copy['date_to']) ?></span>
                <input type="date" name="date_to" value="<?= soc_e($filters['date_to']) ?>">
            </label>
            <label>
                <span><?= soc_e($copy['attack_type']) ?></span>
                <select name="attack">
                    <option value="all"><?= soc_e($copy['all']) ?></option>
                    <option value="sqli" <?= $filters['attack'] === 'sqli' ? 'selected' : '' ?>>SQLi</option>
                    <option value="xss" <?= $filters['attack'] === 'xss' ? 'selected' : '' ?>>XSS</option>
                    <option value="bruteforce" <?= $filters['attack'] === 'bruteforce' ? 'selected' : '' ?>>Brute Force</option>
                </select>
            </label>
            <label>
                <span><?= soc_e($copy['severity']) ?></span>
                <select name="severity">
                    <option value="all"><?= soc_e($copy['all']) ?></option>
                    <?php foreach (['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'] as $severity): ?>
                        <option value="<?= soc_e($severity) ?>" <?= $filters['severity'] === $severity ? 'selected' : '' ?>><?= soc_e(soc_severity_label($severity)) ?></option>
                    <?php endforeach; ?>
                </select>
            </label>
            <label>
                <span><?= soc_e($copy['status']) ?></span>
                <select name="status">
                    <?php foreach (array_keys(SOC_STATUSES) as $status): ?>
                        <option value="<?= soc_e($status) ?>" <?= $filters['status'] === $status ? 'selected' : '' ?>><?= soc_e(soc_status_label($status)) ?></option>
                    <?php endforeach; ?>
                </select>
            </label>
            <div class="report-actions">
                <button type="submit"><?= soc_e($copy['preview']) ?></button>
                <button type="submit" name="format" value="pdf"><?= soc_e($copy['generate_pdf']) ?></button>
            </div>
        </form>
    </article>

    <article class="panel-card">
        <div class="panel-head">
            <h2><?= soc_e($copy['preview']) ?></h2>
            <span><?= soc_e($filters['date_from']) ?> - <?= soc_e($filters['date_to']) ?></span>
        </div>
        <div class="report-summary">
            <div><span>Total</span><strong><?= soc_e($stats['total']) ?></strong></div>
            <div><span><?= soc_e($copy['global_score']) ?></span><strong class="score-report-value"><?= soc_e($detection['score_global']) ?> / <?= soc_e($detection['score_level']) ?></strong></div>
            <div><span>SQLi</span><strong><?= soc_e($stats['sqli']) ?></strong><small><?= soc_e($attackPercentages['sqli']['percent'] ?? 0) ?>%</small></div>
            <div><span>XSS</span><strong><?= soc_e($stats['xss']) ?></strong><small><?= soc_e($attackPercentages['xss']['percent'] ?? 0) ?>%</small></div>
            <div><span>Brute Force</span><strong><?= soc_e($stats['brute_force']) ?></strong><small><?= soc_e($attackPercentages['bruteforce']['percent'] ?? 0) ?>%</small></div>
        </div>

        <div class="report-percent-card">
            <div class="panel-head">
                <h3><?= soc_e($copy['attack_percentages']) ?></h3>
                <span><?= soc_e($copy['dominant_attack']) ?>: <?= soc_e($payload['dominant_attack']['label']) ?> <?= soc_e($payload['dominant_attack']['percent']) ?>%</span>
            </div>
            <?php foreach ($payload['attack_percentages'] as $item): ?>
                <div class="report-percent-row">
                    <span><?= soc_e($item['label']) ?></span>
                    <i><em style="width: <?= soc_e($item['percent']) ?>%; background: <?= soc_e($item['color']) ?>;"></em></i>
                    <strong><?= soc_e($item['count']) ?> · <?= soc_e($item['percent']) ?>%</strong>
                </div>
            <?php endforeach; ?>
        </div>

        <?php if (!$payload['cases']): ?>
            <p class="empty-note"><?= soc_e($copy['no_alerts']) ?></p>
        <?php endif; ?>

        <div class="report-cases">
            <?php foreach ($payload['cases'] as $case): ?>
                <section class="report-case">
                    <div class="panel-head">
                        <div>
                            <h3><?= soc_e($case['label']) ?></h3>
                            <p><?= soc_e($case['count']) ?> <?= soc_e($copy['cases']) ?> · <?= soc_e($copy['latest_seen']) ?> <?= soc_e($case['latest_seen']) ?></p>
                        </div>
                        <span class="pill severity-<?= soc_e(strtolower($case['severity'])) ?>"><?= soc_e(soc_severity_label($case['severity'])) ?></span>
                    </div>
                    <?php if ($options['include_mitre']): ?>
                        <p class="report-mitre">
                            <span class="mitre-chip"><?= soc_e($case['mitre_id']) ?></span>
                            <?= soc_e($case['mitre_tactic']) ?> · <?= soc_e($case['mitre_technique']) ?>
                        </p>
                    <?php endif; ?>
                    <?php if ($case['sources']): ?>
                        <p class="report-line"><strong><?= soc_e($copy['main_sources']) ?>:</strong> <?= soc_e(implode(', ', $case['sources'])) ?></p>
                    <?php endif; ?>
                    <p class="report-line"><strong><?= soc_e($copy['incident_analysis']) ?>:</strong> <?= soc_e($case['incident']) ?></p>
                    <?php if ($options['include_response'] && $case['responses']): ?>
                        <h4><?= soc_e($copy['responses']) ?></h4>
                        <ul class="report-list">
                            <?php foreach ($case['responses'] as $response): ?><li><?= soc_e($response) ?></li><?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                    <h4><?= soc_e($copy['improvements']) ?></h4>
                    <ul class="report-list">
                        <?php foreach ($case['improvements'] as $improvement): ?><li><?= soc_e($improvement) ?></li><?php endforeach; ?>
                    </ul>
                </section>
            <?php endforeach; ?>
        </div>

        <?php
        $timeline = $payload['attack_timeline'];
        $timelineMax = max(1, (int)$timeline['max']);
        $timelinePoints = array_slice($timeline['points'], -14);
        ?>
        <section class="report-timeline-card">
            <div class="panel-head">
                <div>
                    <h3><?= soc_e($copy['attack_timeline']) ?></h3>
                    <p><?= soc_e($copy['timeline_hint']) ?></p>
                </div>
                <span><?= soc_e($copy['period_min']) ?>: <?= soc_e($timeline['min']) ?> · <?= soc_e($copy['period_max']) ?>: <?= soc_e($timeline['max']) ?></span>
            </div>
            <div class="report-timeline-chart">
                <?php foreach ($timelinePoints as $point): ?>
                    <div class="timeline-period">
                        <div class="timeline-bar" title="<?= soc_e($point['label']) ?>: <?= soc_e($point['total']) ?>">
                            <?php foreach ([
                                'sqli' => '#dc2626',
                                'xss' => '#7c3aed',
                                'bruteforce' => '#f59e0b',
                            ] as $key => $color): ?>
                                <?php $height = ((int)$point[$key] / $timelineMax) * 100; ?>
                                <?php if ((int)$point[$key] > 0): ?>
                                    <span style="height: <?= soc_e(round($height, 2)) ?>%; background: <?= soc_e($color) ?>;"></span>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </div>
                        <strong><?= soc_e($point['total']) ?></strong>
                        <small><?= soc_e($point['label']) ?></small>
                    </div>
                <?php endforeach; ?>
            </div>
            <div class="timeline-legend">
                <span><i style="background:#dc2626"></i>SQLi</span>
                <span><i style="background:#7c3aed"></i>XSS</span>
                <span><i style="background:#f59e0b"></i>Brute Force</span>
            </div>
        </section>
    </article>
</section>
<?php soc_shell_end(); ?>
